services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-dbmovie}
    ports:
        - ${DB_PORT:-5432}:5432
    volumes:
        - ./MovieApi/_sql/pg:/docker-entrypoint-initdb.d
        - ./MovieApi/_sql/scripts:/usr/src 

  api:
    build:
      context: .
      args:
        - PASSWORD_ENV_SEEDED=${PASSWORD_ENV_SEEDED}
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - PASSWORD_ENV_SEEDED=some.long.password.fllkwefiwejf23049uwlekjf.sEFWEFGR98^&$
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    