CREATE TABLE "Movies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Year" integer NOT NULL,
    "Duration" integer,
    CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
);


